name: Publish action

on:
  create:
    tag:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk 17
        uses: actions/setup-java@v1
        with:
          java-version: "17"
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: Publish Wandering Fighters 
        uses: Kir-Antipov/mc-publish@v2.1
        with:
          curseforge-id: 695587
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files-primary: build/libs/!(*-@(dev|sources)).jar
          files-secondary: build/libs/*-@(dev|sources).jar
          version-type: release
          loaders: forge
          game-versions: 1.19.3
          java: 17
          name: ""
          changelog: "https://github.com/Witixin1512/WanderingFIghters/commits/main"
